import type { CollectionConfig } from 'payload'
import { adminOrAboveAccess, anyLoggedInAccess, superAdminAccess } from '../access/roles'

export const AgentRuns: CollectionConfig = {
  slug: 'agent-runs',
  admin: {
    useAsTitle: 'agentName',
  },
  access: {
    create: adminOrAboveAccess,
    read: anyLoggedInAccess,
    update: adminOrAboveAccess,
    delete: superAdminAccess,
  },
  fields: [
    {
      name: 'agentName',
      type: 'select',
      required: true,
      options: [
        { label: 'Product Agent', value: 'product' },
        { label: 'Architect Agent', value: 'architect' },
        { label: 'Reviewer Agent', value: 'reviewer' },
        { label: 'Orchestrator', value: 'orchestrator' },
        // Milestone 1 addition
        { label: 'Planner (M1)', value: 'planner' },
      ],
    },
    {
      name: 'codingRequest',
      type: 'relationship',
      relationTo: 'coding-requests',
      required: true,
    },
    {
      name: 'status',
      type: 'select',
      defaultValue: 'running',
      options: [
        { label: 'Running', value: 'running' },
        { label: 'Completed', value: 'completed' },
        { label: 'Failed', value: 'failed' },
      ],
    },
    {
      name: 'input',
      type: 'json',
      admin: {
        description: 'Input passed to the agent',
      },
    },
    {
      name: 'output',
      type: 'json',
      admin: {
        description: 'Output returned by the agent',
      },
    },
    {
      name: 'durationMs',
      type: 'number',
      admin: {
        description: 'Execution time in milliseconds',
      },
    },
    {
      name: 'errorMessage',
      type: 'text',
    },
    // ─── Milestone 1 additions (additive, non-breaking) ──────────────────────
    {
      name: 'runType',
      type: 'select',
      defaultValue: 'codegen',
      options: [
        { label: 'Code Generation', value: 'codegen' },
        { label: 'Planning (M1)', value: 'planning' },
        { label: 'Fix', value: 'fix' },
      ],
      admin: { description: 'Type of agent run' },
    },
    {
      name: 'branchName',
      type: 'text',
      admin: { description: 'GitHub branch created for this run (e.g. codehive/plan-123)' },
    },
    {
      name: 'prUrl',
      type: 'text',
      admin: { description: 'GitHub Pull Request URL created for this run' },
    },
    {
      name: 'planMarkdown',
      type: 'textarea',
      admin: { description: 'Full plan markdown generated by the planning agent' },
    },
  ],
}
